// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUxOZzFxT5ii6mqADgCRpQLQ1fABUsbh4',
    appId: '1:1105408089:android:275e71633401a8979f8148',
    messagingSenderId: '1105408089',
    projectId: 'chatapp-a1340',
    storageBucket: 'chatapp-a1340.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcg8voayCCVPyhKxWR2Q_QXwmxLAUh5IM',
    appId: '1:1105408089:ios:f8e6c9012b9c791b9f8148',
    messagingSenderId: '1105408089',
    projectId: 'chatapp-a1340',
    storageBucket: 'chatapp-a1340.appspot.com',
    androidClientId: '1105408089-vaq6q9vkgdlhiss3v59p6icv2pfcgic5.apps.googleusercontent.com',
    iosClientId: '1105408089-jdbmon194p7f6rdr9jt9kot3rhp02lla.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChatapp',
  );
}
